# -*- coding: utf-8 -*-
"""data_preprocess.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gi7HI-_sC-VXUZT2IQwfYpmrWr2ON7ED
"""

from google.colab import drive
drive.mount('/content/drive')

"""# for single_frame_CNN

"""

import cv2
import os 
import random
path2data = 'drive/MyDrive/split_imges'
store_folder = "drive/MyDrive/single_cnn"
os.mkdir(store_folder)
listofph = os.listdir(path2data)
for ph in listofph:
  path2ph = os.path.join(path2data,ph)
  if not os.path.exists(store_folder + '/' + str(ph)):
        os.mkdir(store_folder + '/' + str(ph))
  listofcats = os.listdir(path2ph)
  if '.DS_Store' in listofcats:
      listofcats.remove('.DS_Store')
  for cat in listofcats:
      path2cat = os.path.join(path2ph,cat)
      if not os.path.exists(store_folder + '/' + str(ph) + '/' + str(cat)):
        os.mkdir(store_folder + '/' + str(ph) + '/' + str(cat))
      listofts = os.listdir(path2cat)
      if '.DS_Store' in listofts:
          listofts.remove('.DS_Store')
      for ts in listofts :
          path2ts = os.path.join(path2cat,ts)
          listofimgs  = os.listdir(path2ts)
          if '.DS_Store' in listofimgs:
            listofimgs.remove('.DS_Store')
          img = random.choice(listofimgs)
          path2img = os.path.join(path2ts,img)
          image = cv2.imread(path2img)
          path2store = os.path.join(store_folder + '/' + str(ph) + '/' + str(cat) + '/' + str(ts) + '.jpg')
          cv2.imwrite(path2store,image)

listofcats = os.listdir(store_folder)
for cat in listofcats:
  path2cat = os.path.join(store_folder,cat)
  listofimgs = os.listdir(path2cat)
  print(cat,len(listofimgs))

"""# for early_fusion

"""

import cv2
import numpy as np
import os
from PIL import Image
import glob
from natsort import natsorted

path2data = "drive/MyDrive/split_imges"
store_folder = "drive/MyDrive/earlyfusion"
os.mkdir(store_folder)
imgs = []
listofph = os.listdir(path2data)
for ph in listofph:
  path2ph = os.path.join(path2data,ph)
  if not os.path.exists(store_folder + '/' + str(ph)):
    os.mkdir(store_folder + '/' + str(ph))
  listofcats = os.listdir(path2ph)
  for cat in listofcats:
    print(cat)
    path2cat = os.path.join(path2ph,cat)
    if not os.path.exists(store_folder + '/' + str(ph) + '/' + str(cat)):
      os.mkdir(store_folder + '/' + str(ph) + '/' + str(cat))
    listofts = os.listdir(path2cat)
    if '.DS_Store' in listofts:
          listofts.remove('.DS_Store')
    for i,ts in enumerate(listofts):   
      path2ts = os.path.join(path2cat,ts)
      listofimgs = os.listdir(path2ts)
      if '.DS_Store' in listofimgs:
          listofimgs.remove('.DS_Store')
      listofimgs_sorted = natsorted(glob.glob(path2ts + '/*.jpg'))
      for path2img in listofimgs_sorted:
          img = cv2.imread(path2img)
          im_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
          im_gray = cv2.resize(im_gray,(224,224))
          imgs.append(im_gray)
      if len(imgs) == 16:
          im = cv2.merge(imgs)
          np.save(store_folder + '/' + str(ph) + '/' + str(cat) + '/' + str(ts),im)
          imgs = []
      else:
          imgs = []

import numpy as np
a = np.load("/content/drive/MyDrive/earlyfusion/train/run/video66.npy")
print(a.shape)

listofcats = os.listdir(store_folder)
for cat in listofcats:
  path2cat = os.path.join(store_folder,cat)
  listofnps = os.listdir(path2cat)
  print(cat,len(listofnps))

"""# for late_fusion 3dcnn cnn_lstm

"""

import os
import cv2
import glob
import numpy as np
import torchvision.transforms.functional as TF

path2data = "drive/MyDrive/split_imges"
store_folder = "drive/MyDrive/latefusion"
#os.mkdir(store_folder)
listofph = os.listdir(path2data)
for ph in listofph:
  path2ph = os.path.join(path2data,ph)
  if not os.path.exists(store_folder + '/' + str(ph)):
    os.mkdir(store_folder + '/' + str(ph))
  listofcats = os.listdir(path2ph)
  data = []
  if ".DS_Store" in listofcats:
    listofcats.remove(".DS_Store")
  for cat in listofcats:
    print(cat)
    path2cat = os.path.join(path2ph,str(cat))
    if not os.path.exists(store_folder + '/' + str(ph) + '/' + str(cat)):
      os.mkdir(store_folder + '/' + str(ph) + '/' + str(cat))
    listofts = os.listdir(path2cat)
    if ".DS_Store" in listofts:
      listofts.remove(".DS_Store")
    for i,ts in enumerate(listofts):
      path2ts = os.path.join(path2cat,str(ts))
      listofimgs = os.listdir(path2ts)
      if ".DS_Store" in listofimgs:
        listofimgs.remove(".DS_Store")
      if len(listofimgs) != 16:
        listofts.remove(ts)
      listofimgs_sorted = natsorted(glob.glob(path2ts + '/*.jpg'))
      for path2img in listofimgs_sorted:
        img = cv2.imread(path2img)
        img = cv2.resize(img,(224,224))
        data.append(img)
      data = np.array(data)
      if data.shape == (16,224,224,3):
          np.save(store_folder + '/' + str(ph) + '/' + str(cat) +  '/' + str(ts),data)
          data = []
      else:
          data = []

listofcats = os.listdir(store_folder)
for cat in listofcats:
  path2cat = os.path.join(store_folder,cat)
  listofnps = os.listdir(path2cat)
  print(cat,len(listofnps))

